base_model: Rakuten/RakutenAI-7B-instruct
model_type: MistralForCausalLM
tokenizer_type: LlamaTokenizer

load_in_8bit: false
load_in_4bit: false

# Phase 1: person_dummy only (negative case calibration)
datasets:
  - path: data/train/person_dummy_segments.jsonl
    type: input_output
    train_on_inputs: false

dataset_prepared_path: last_run_prepared
val_set_size: 0
output_dir: ./outputs/lora-out-phase1

test_datasets:
  - path: data/train/hawks_val_segments.jsonl
    type: input_output

adapter: lora
lora_model_dir:

sequence_len: 4096
sample_packing: true
eval_sample_packing: false
pad_to_sequence_len: true

lora_r: 32
lora_alpha: 16
lora_dropout: 0
lora_target_linear: true
lora_target_modules:
  - gate_proj
  - down_proj
  - up_proj
  - q_proj
  - v_proj
  - k_proj
  - o_proj


use_wandb: false

use_mlflow: true
mlflow_tracking_uri: ./mlruns
mlflow_experiment_name: rakuten-lora-baseline
mlflow_run_name: null
hf_mlflow_log_artifacts: false

gradient_accumulation_steps: 2
micro_batch_size: 8
max_steps: 100
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

bf16: auto
tf32: true

gradient_checkpointing: true
resume_from_checkpoint:
logging_steps: 1
flash_attention: true

loss_watchdog_threshold: 5.0
loss_watchdog_patience: 3

warmup_ratio: 0.1
evals_per_epoch: 4
saves_per_epoch: 1
weight_decay: 0.0
special_tokens:

# multi-gpu configs
deepspeed: src/deepspeed_configs/zero2.json

dataloader_num_workers: 8
dataloader_prefetch_factor: 4
dataloader_pin_memory: true

lora_mlp_kernel: true
lora_qkv_kernel: true
lora_o_kernel: true
