base_model: Rakuten/RakutenAI-7B-instruct
# optionally might have model_type or tokenizer_type
model_type: MistralForCausalLM
tokenizer_type: LlamaTokenizer

# Automatically upload checkpoint and final model to HF
# hub_model_id: username/custom_model_name

load_in_8bit: true
load_in_4bit: false

datasets:
  - path: data/train/hawks_train.json
    type: alpaca
dataset_prepared_path: last_run_prepared
val_set_size: 0.1
output_dir: ./outputs/qlora-out

adapter: lora
lora_model_dir:

sequence_len: 2048
sample_packing: true
eval_sample_packing: false
pad_to_sequence_len: true

lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true
lora_target_modules:
  - gate_proj
  - down_proj
  - up_proj
  - q_proj
  - v_proj
  - k_proj
  - o_proj

# lora optim, see docs/small_model_architecture.md.
lora_mlp_kernel: true
lora_qkv_kernel: true
lora_o_kernel: true

use_wandb: false

use_mlflow: true
# この辺何書いたらいいかわかんない
mlflow_tracking_uri: str | None
mlflow_experiment_name: str | None
mlflow_run_name: str | None
hf_mlflow_log_artifacts: bool | None

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 1
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

bf16: auto
tf32: false

gradient_checkpointing: true
resume_from_checkpoint:
logging_steps: 1
flash_attention: true

loss_watchdog_threshold: 5.0
loss_watchdog_patience: 3

warmup_ratio: 0.1
evals_per_epoch: 4
saves_per_epoch: 1
weight_decay: 0.0
special_tokens:

# save_first_step: true  # uncomment this to validate checkpoint saving works with your config

# multi-gpu configs
deepspeed: deepspeed_configs/zero2.json
