base_model: Rakuten/RakutenAI-7B-instruct
model_type: MistralForCausalLM
tokenizer_type: LlamaTokenizer

load_in_8bit: true
load_in_4bit: false

# Phase 2: hawks (positive examples) + person_dummy replay (20% for FP mitigation)
datasets:
  - path: data/train/hawks_train.json
    type: alpaca
    field_instruction: instruction
    field_input: input
    field_output: output
  - path: data/train/person_dummy_2025-12-23-1817.json
    type: alpaca
    field_instruction: instruction
    field_input: input
    field_output: output
    weight: 0.2

dataset_prepared_path: last_run_prepared
val_set_size: 0.1
output_dir: ./outputs/lora-out-phase2

adapter: lora
lora_model_dir:

sequence_len: 2048
sample_packing: true
eval_sample_packing: false
pad_to_sequence_len: true

lora_r: 32
lora_alpha: 16
lora_dropout: 0
lora_target_linear: true
lora_target_modules:
  - gate_proj
  - down_proj
  - up_proj
  - q_proj
  - v_proj
  - k_proj
  - o_proj

# lora kernel optimizations enabled (dropout must be 0)
lora_mlp_kernel: true
lora_qkv_kernel: true
lora_o_kernel: true

use_wandb: false

use_mlflow: true
mlflow_tracking_uri: ./mlruns
mlflow_experiment_name: rakuten-lora-baseline
mlflow_run_name: null
hf_mlflow_log_artifacts: false

gradient_accumulation_steps: 2
micro_batch_size: 8
num_epochs: 1
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0001

bf16: auto
tf32: false

gradient_checkpointing: true
# Resume from Phase 1 checkpoint
resume_from_checkpoint: ./outputs/lora-out-phase1/checkpoint-final
logging_steps: 1
flash_attention: true

loss_watchdog_threshold: 5.0
loss_watchdog_patience: 3

warmup_ratio: 0.05
evals_per_epoch: 4
saves_per_epoch: 1
weight_decay: 0.0
special_tokens:

# multi-gpu configs
deepspeed: deepspeed_configs/zero2.json
